# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - frontendprojectx

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_b7455ec194c044ffad0429b4b4a41bac }}
        password: ${{ secrets.AzureAppService_ContainerPassword_9a3b92c288cf459abc0a0ac9262ee9b6 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_b7455ec194c044ffad0429b4b4a41bac }}/clientportalx/angular-frontend:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'frontendprojectx'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_c66986e70bef4020ad1c3ee0f74de76d }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_b7455ec194c044ffad0429b4b4a41bac }}/clientportalx/angular-frontend:${{ github.sha }}'